#include "core.hpp"
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <map>
using namespace v35;
struct Observation{int turn=0,my_land=0,my_army=0,opp_land=0,opp_army=0;std::vector<int>type,owner,army;};
struct Action{int kind=1,row=0,col=0,dir=0,split=0;};
class Agent{int player_,h_,w_,n_,general_=-1,event_=0,contact_turn_=-1,next_packet_=1,last_turn_=-1,pending_to_=-1;long pending_packet_=0;Graph g_;CastleChoice castles_;Belief belief_;OpponentModel opponent_;FrontManager fronts_;std::map<long,Packet> packets_;std::vector<long> packet_at_;std::vector<int>last_owner_,last_army_,opp_land_history_,opp_army_history_;std::vector<double>times_;long cycles_=0,legitimate_reversals_=0,objective_changes_=0,evacuations_=0,mobilizations_=0;ProductionState production_=ProductionState::HEALTHY;std::array<CastleState,2> castle_state_{{CastleState::PLANNED,CastleState::PLANNED}};
 int dir(int a,int b)const{for(int d=0;d<4;++d)if(g_.neighbor(a,d)==b)return d;return 0;}Action move(int a,int b,bool split=false)const{return {0,a/w_,a%w_,dir(a,b),split};}Action pass()const{return {};}
 bool source(const Observation&o,int x)const{return x>=0&&o.owner[x]==1&&o.army[x]>1;}
 void init(const Observation&o){g_={h_,w_,{},{},{}};g_.passable.resize(n_);for(int x=0;x<n_;++x){g_.passable[x]=o.type[x]!=2&&o.type[x]!=5;if(o.type[x]==4&&o.owner[x]==1)general_=x;}g_.build();castles_=plan_castles(g_,general_);belief_.initialise(g_,general_);last_owner_=o.owner;last_army_=o.army;packet_at_.assign(n_,0);std::fprintf(stderr,"[v35_plan] c1=%d cost1=%d deadline1=150 c2=%d cost2=%d deadline2=250 total=%d c3=%d\n",castles_.c1,castles_.cost1,castles_.c2,castles_.cost2,castles_.total,castles_.c3);}
 void reconcile(const Observation&o){if(pending_packet_&&pending_to_>=0){auto it=packets_.find(pending_packet_);if(it!=packets_.end()&&o.owner[pending_to_]==1){auto&p=it->second;if(p.cell>=0&&p.cell<n_&&packet_at_[p.cell]==p.id)packet_at_[p.cell]=0;p.cell=pending_to_;p.army=o.army[p.cell];p.path.push_back(p.cell);while(p.path.size()>12)p.path.pop_front();packet_at_[p.cell]=p.id;}else if(it!=packets_.end())packets_.erase(it);}pending_packet_=0;pending_to_=-1;for(auto it=packets_.begin();it!=packets_.end();){if(it->second.cell<0||o.owner[it->second.cell]!=1){it=packets_.erase(it);}else{it->second.army=o.army[it->second.cell];++it;}}}
 Packet& assignment(const Observation&o,int x,int target,int front,PacketRole role,Reason reason){long id=packet_at_[x];Packet*p=id&&packets_.count(id)?&packets_[id]:nullptr;if(!p){Packet fresh;fresh.id=next_packet_++;fresh.cell=x;fresh.army=o.army[x];fresh.target=target;fresh.front_id=front;fresh.role=role;fresh.assigned_turn=o.turn;fresh.event_version=event_;fresh.assignment_reason=reason;fresh.path.push_back(x);packets_[fresh.id]=fresh;packet_at_[x]=fresh.id;p=&packets_[fresh.id];++objective_changes_;}else if(p->target!=target||p->front_id!=front||p->role!=role){p->target=target;p->front_id=front;p->role=role;p->assigned_turn=o.turn;p->event_version=event_;p->assignment_reason=reason;p->idle=0;++objective_changes_;}return *p;}
 bool safe_step(const Observation&o,int x,int y)const{if(y<0||!g_.passable[y])return false;if(o.owner[y]==2&&o.army[x]-1<=o.army[y])return false;for(int d=0;d<4;++d){int z=g_.neighbor(y,d);if(z>=0&&o.owner[z]==2&&o.army[z]>=o.army[x]-1-(o.owner[y]==2?o.army[y]:0))return false;}return true;}
 int tactical_next(const Observation&o,int x,int target)const{int best=-1,bd=INF;for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(safe_step(o,x,y)&&g_.dist[y][target]<bd)best=y,bd=g_.dist[y][target];}return best;}
 int reserve(const Observation&o,int x)const{if(x==general_)return std::max(5,o.opp_army/12);if(x==castles_.c1||x==castles_.c2)return 2;for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&o.owner[y]==2)return std::max(2,o.army[y]+1);}return 1;}
 std::vector<std::pair<int,int>> feeders(const Observation&o,int target)const{std::vector<std::pair<int,int>>f;for(int x=0;x<n_;++x)if(source(o,x)&&g_.dist[x][target]<INF)f.push_back({o.army[x]-reserve(o,x),g_.dist[x][target]});return f;}
 Action act(const Observation&o){auto begin=std::chrono::steady_clock::now();if(g_.passable.empty())init(o);else reconcile(o);bool contact=false;int enemy=-1,enemy_army=0,small=0,visible=0;std::vector<int>sizes;std::vector<std::pair<int,int>>contacts;for(int x=0;x<n_;++x){if(o.owner[x]==2){contact=true;++visible;sizes.push_back(o.army[x]);contacts.push_back({x,o.army[x]});if(o.army[x]<=5)++small;if(o.army[x]>enemy_army)enemy_army=o.army[x],enemy=x;if(o.type[x]==4&&!belief_.confirmed()){belief_.confirm(x);++event_;}}if(o.type[x]>=0&&o.owner[x]!=2)belief_.eliminate(x);}auto fc=fronts_.update(g_,o.turn,contacts,general_);if(fc.added||fc.closed)++event_;if(contact&&contact_turn_<0){contact_turn_=o.turn;++event_;}for(int x=0;x<n_;++x)if(o.owner[x]==2)for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&last_owner_[y]==2&&last_army_[y]>=o.army[x]-2)belief_.back_project(g_,y,x);}opp_land_history_.push_back(o.opp_land);opp_army_history_.push_back(o.opp_army);auto slope=[&](const std::vector<int>&v,int window){return v.size()>1?double(v.back()-v[v.size()-1-std::min<int>(window,v.size()-1)])/std::min<int>(window,v.size()-1):0.;};OpponentEvidence e;e.turn=o.turn;e.samples=visible;e.land_velocity=(slope(opp_land_history_,5)+slope(opp_land_history_,20))/2;e.army_velocity=(slope(opp_army_history_,10)+slope(opp_army_history_,50))/2;e.concentration=o.opp_army?double(enemy_army)/o.opp_army:0;if(!sizes.empty()){std::sort(sizes.begin(),sizes.end());e.median_packet=sizes[sizes.size()/2];}e.fronts=fronts_.active_count();e.closing=enemy>=0?std::max(0,12-g_.dist[enemy][general_])/12.:0;e.castles=0;for(int x=0;x<n_;++x)e.castles+=(o.owner[x]==2&&o.type[x]==3);e.activity=visible?std::min(1.,visible/4.):0;e.reaction_ratio=small>3?.3:0;opponent_.update(e);auto adapt=opponent_.adaptation();int land_gap=o.opp_land-o.my_land;auto oldprod=production_;production_=land_gap>18?ProductionState::SEVERE_DEFICIT:land_gap>8?ProductionState::SOFT_DEFICIT:ProductionState::HEALTHY;if(oldprod!=production_)++event_;
 for(int i=0;i<2;++i){int site=i?castles_.c2:castles_.c1;if(site>=0&&o.owner[site]==1&&o.type[site]==3)castle_state_[i]=CastleState::BUILT;}auto f1=castle_state_[0]==CastleState::BUILT?FundingForecast{}:forecast(o.turn,150,castles_.cost1,castles_.c1>=0&&o.owner[castles_.c1]==1?o.army[castles_.c1]:0,feeders(o,castles_.c1));auto f2=castle_state_[1]==CastleState::BUILT?FundingForecast{}:forecast(o.turn,250,castles_.cost2,castles_.c2>=0&&o.owner[castles_.c2]==1?o.army[castles_.c2]:0,feeders(o,castles_.c2));auto b=budget(o.my_army,general_>=0?o.army[general_]:0,f1.feasible?f1.required:0,f2.feasible?f2.required:0,contact,adapt.attack);b.expansion=int(b.expansion*std::max(.4,adapt.expansion/.3));b.search=int(b.search*std::max(.4,adapt.search/.25));std::vector<Candidate> c;
 // Tier 0: captures and immediate general defense.
 for(int x=0;x<n_;++x)if(source(o,x))for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y<0||!g_.passable[y])continue;if(o.type[y]==4&&o.owner[y]==2&&o.army[x]-1>o.army[y])c.push_back({0,x,y,0,1,Reason::TERMINAL_CAPTURE,false});if(y==general_&&o.owner[x]==2){} }
 if(enemy>=0&&g_.dist[enemy][general_]<=2)for(int x=0;x<n_;++x)if(source(o,x)){int y=g_.next[x][general_];if(y>=0&&o.owner[y]==1)c.push_back({0,x,y,0,double(o.army[x]),Reason::GENERAL_EMERGENCY,false});}
 // Tier 1: deadline funding/building.
 for(auto [site,f,index]:{std::tuple{castles_.c1,f1,0},std::tuple{castles_.c2,f2,1}})if(site>=0&&castle_state_[index]!=CastleState::BUILT&&(index==0||castle_state_[0]==CastleState::BUILT)){if(o.owner[site]==1&&o.type[site]==1&&o.army[site]>=(index?castles_.cost2:castles_.cost1)){castle_state_[index]=CastleState::BUILDABLE;c.push_back({1,site,site,2,100,Reason::CASTLE_DEADLINE,false});}else if(f.must_fund){castle_state_[index]=CastleState::FUNDING;for(int x=0;x<n_;++x)if(source(o,x)){int y=tactical_next(o,x,site);if(y>=0)c.push_back({1,x,y,0,double(o.army[x])/std::max(1,g_.dist[x][site]),Reason::CASTLE_DEADLINE,false});}}else castle_state_[index]=o.owner[site]==1?CastleState::WAITING_FOR_JIT:CastleState::ACQUIRING_SITE;}
 // Tier 2: war mobilization and mandatory rear evacuation, always FULL-1.
 auto primary=fronts_.primary();int sink=belief_.confirmed()?belief_.confirmed_cell():(primary?primary->anchor:belief_.top());int remaining_war=b.war,remaining_search=b.search;for(int x=0;x<n_;++x)if(source(o,x)){int r=x/w_,col=x%w_,edge=std::min({r,h_-1-r,col,w_-1-col});bool rear=edge<=1||g_.degree(x)<=1;int surplus=o.army[x]-reserve(o,x);if(surplus<=0||x==castles_.c1||x==castles_.c2)continue;Reason why=contact?Reason::WAR_MOBILIZATION:Reason::REAR_EVACUATION;int objective=(sink==x?general_:sink);Packet&p=assignment(o,x,objective,primary?primary->id:-1,contact?PacketRole::FRONT:PacketRole::FREE_SURPLUS_RELOCATION,why);int y=objective>=0?tactical_next(o,x,objective):-1;if(y<0)continue;bool allowed=route_allowed(p,y,g_.dist[y][objective],g_.dist[x][objective],event_,why);if(!allowed){++cycles_;++p.revisits;continue;}if(p.event_version!=event_){++legitimate_reversals_;p.event_version=event_;}if(contact&&remaining_war>0){c.push_back({2,x,y,0,double(surplus*g_.dist[x][sink]),why,false});remaining_war-=std::min(remaining_war,surplus);}else if(rear&&remaining_search>0){c.push_back({2,x,y,0,double(surplus*g_.dist[x][sink]),why,false});remaining_search-=std::min(remaining_search,surplus);}}
 // Tier 3: production opportunity before tick, then useful expansion.
 int until=50-o.turn%50;int expansion_left=b.expansion;for(int x=0;x<n_&&expansion_left>0;++x)if(source(o,x))for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&g_.passable[y]&&o.owner[y]==0&&o.army[x]-1>o.army[y]&&o.army[y]+1<=expansion_left){int tier=(until<=5||production_==ProductionState::SEVERE_DEFICIT)?3:4;c.push_back({tier,x,y,0,double(g_.degree(y)*10-o.army[y]),tier==3?Reason::PRODUCTION_TICK:Reason::SEARCH_PROGRESS,false});}}
 Candidate q=schedule(c);Action a=pass();if(q.kind==2)a={2,q.from/w_,q.from%w_,0,0};else if(q.from>=0&&q.to>=0)a=move(q.from,q.to,q.split);if(a.kind==0){int x=a.row*w_+a.col,y=g_.neighbor(x,a.dir);if(!source(o,x)||y<0||!g_.passable[y])a=pass();else{if(packet_at_[x])pending_packet_=packet_at_[x],pending_to_=y;if(q.reason==Reason::REAR_EVACUATION)++evacuations_;else if(q.reason==Reason::WAR_MOBILIZATION)++mobilizations_;}}
 last_turn_=o.turn;last_owner_=o.owner;last_army_=o.army;double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();times_.push_back(ms);if(std::getenv("JURAJ_V35_TRACE")){auto&p=opponent_.confidence();std::fprintf(stderr,"[v35_production] turn=%d state=%d land=%d/%d until_tick=%d\n",o.turn,(int)production_,o.my_land,o.opp_land,until);std::fprintf(stderr,"[v35_castles] turn=%d c1_req=%d feasible=%d must=%d c2_req=%d feasible=%d must=%d\n",o.turn,f1.required,f1.feasible,f1.must_fund,f2.required,f2.feasible,f2.must_fund);std::fprintf(stderr,"[v35_front] turn=%d contact=%d war=%d free=%d\n",o.turn,contact_turn_,b.war,b.free);std::fprintf(stderr,"[v35_opponent] turn=%d response=%s",o.turn,adapt.response.c_str());for(double z:p)std::fprintf(stderr," %.3f",z);std::fputc('\n',stderr);std::fprintf(stderr,"[v35_search] turn=%d top=%d entropy=%.3f\n",o.turn,belief_.top(),belief_.entropy());}return a;}
 void report(){if(times_.empty())return;std::sort(times_.begin(),times_.end());auto p=[&](double q){return times_[std::min(times_.size()-1,(size_t)std::ceil(q*times_.size())-1)];};double mean=std::accumulate(times_.begin(),times_.end(),0.)/times_.size();std::fprintf(stderr,"[v35_logistics] packets=%zu objective_changes=%ld evacuations=%ld mobilizations=%ld\n[v35_cycles] rejected=%ld allowed_reversals=%ld event_version=%d\n[v35_reaction] contact_turn=%d\n[v35_timing] mean=%.3f p95=%.3f p99=%.3f max=%.3f\n",packets_.size(),objective_changes_,evacuations_,mobilizations_,cycles_,legitimate_reversals_,event_,contact_turn_,mean,p(.95),p(.99),times_.back());}
public:Agent(int p,int h,int w):player_(p),h_(h),w_(w),n_(h*w){}Action decide(const Observation&o){try{return act(o);}catch(...){return pass();}}size_t packet_count()const{return packets_.size();}long rejected_cycles()const{return cycles_;}int event_version()const{return event_;}bool enemy_general_confirmed()const{return belief_.confirmed();}int enemy_general_cell()const{return belief_.confirmed_cell();}int active_fronts()const{return fronts_.active_count();}ProductionState production_state()const{return production_;}~Agent(){report();}};
static bool grid(std::vector<int>&g){for(int&x:g)if(std::scanf("%d",&x)!=1)return false;return true;}
#ifndef V35_AGENT_TEST
int main(){int p,h,w;if(std::scanf("%d %d %d",&p,&h,&w)!=3)return 0;Agent a(p,h,w);Observation o;o.type.resize(h*w);o.owner.resize(h*w);o.army.resize(h*w);while(std::scanf("%d %d %d %d %d",&o.turn,&o.my_land,&o.my_army,&o.opp_land,&o.opp_army)==5){if(!grid(o.type)||!grid(o.owner)||!grid(o.army))break;auto x=a.decide(o);std::printf("%d %d %d %d %d\n",x.kind,x.row,x.col,x.dir,x.split);std::fflush(stdout);}return 0;}

#endif
