#include "core.hpp"
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <map>
#include <set>
using namespace v35;
struct Observation {int turn=0,my_land=0,my_army=0,opp_land=0,opp_army=0;std::vector<int>type,owner,army;};
struct Action {int kind=1,row=0,col=0,dir=0,split=0;};
struct ExecutedMove {int from=-1,to=-1,event=0;ActionClass cls=ActionClass::LOGISTICS;};
struct ActionStats {long expansion=0,neutral=0,enemy=0,war=0,rear=0,search=0,castle=0,defense=0,passes=0;};
struct PassStats {long no_movable=0,no_legal=0,no_safe=0,cycle_blocked=0,no_strategic_candidate=0,other=0,replaced=0;};
class Agent {
 int player_,h_,w_,n_,general_=-1,event_=0,meaningful_contact_turn_=-1,next_packet_=1,pending_to_=-1;long pending_packet_=0;
 Graph g_;CastleChoice castles_;Belief belief_;OpponentModel opponent_;FrontManager fronts_;std::array<CastleState,2> castle_state_{{CastleState::PLANNED,CastleState::PLANNED}};
 std::map<long,Packet>packets_;std::vector<long>packet_at_;std::vector<int>last_owner_,last_army_,land_hist_,opp_land_hist_,opp_army_hist_;std::deque<ExecutedMove>actions_;
 std::array<double,5>credit_{};std::array<long,5>class_actions_{};int expansion_wait_=0,max_fronts_=0,stale_closures_=0;ProductionState production_=ProductionState::HEALTHY;
 long candidate_reject_=0,selected_cycle_prevent_=0,executed_reverse_=0,executed_cycle_=0,objective_changes_=0,allowed_reversals_=0;ActionStats stats_;PassStats pass_stats_;std::vector<double>times_;std::map<int,int>land_snapshots_;long budget_samples_=0,sum_c1_=0,sum_c2_=0,sum_war_=0,sum_expansion_=0,sum_search_=0,sum_free_=0;
 std::array<int,2> castle_start_{{-1,-1}},castle_build_{{-1,-1}},castle_latest_{{-1,-1}},castle_actions_{{0,0}};std::string castle_miss_="none";
 int dir(int a,int b)const{for(int d=0;d<4;++d)if(g_.neighbor(a,d)==b)return d;return 0;}
 Action move(int a,int b,bool split=false)const{return {0,a/w_,a%w_,dir(a,b),split};} Action pass()const{return {};}
 bool source(const Observation&o,int x)const{return x>=0&&o.owner[x]==1&&o.army[x]>1;}
 void init(const Observation&o){g_={h_,w_,std::vector<char>(n_),{}, {}};for(int x=0;x<n_;++x){g_.passable[x]=o.type[x]!=2&&o.type[x]!=5;if(o.type[x]==4&&o.owner[x]==1)general_=x;}g_.build();castles_=plan_castles(g_,general_);belief_.initialise(g_,general_);last_owner_=o.owner;last_army_=o.army;packet_at_.assign(n_,0);std::fprintf(stderr,"[v35_plan] c1=%d cost1=%d c2=%d cost2=%d total=%d\n",castles_.c1,castles_.cost1,castles_.c2,castles_.cost2,castles_.total);}
 int reserve(const Observation&o,int x)const{if(x==general_)return std::max(5,o.opp_army/12);for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&o.owner[y]==2)return std::max(2,o.army[y]+1);}return 1;}
 std::vector<std::pair<int,int>> feeders(const Observation&o,int target)const{std::vector<std::pair<int,int>>f;if(target<0)return f;for(int x=0;x<n_;++x)if(source(o,x)&&g_.dist[x][target]<INF){int surplus=std::max(0,o.army[x]-reserve(o,x));if(surplus)f.push_back({surplus,g_.dist[x][target]});}return f;}
 bool enemy_adjacent_ours(const Observation&o,int x)const{for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&o.owner[y]==1)return true;}return false;}
 bool moved_enemy(const Observation&o,int x)const{if(o.owner[x]!=2||o.army[x]<=1)return false;if(last_owner_[x]==2&&last_army_[x]!=o.army[x])return true;for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&last_owner_[y]==2&&last_army_[y]>1&&last_army_[y]>=o.army[x]-2&&last_army_[x]<=1)return true;}return false;}
 bool safe_attack(const Observation&o,int x,int y)const{if(o.owner[y]!=2||o.army[x]-1<=o.army[y])return false;int remaining=o.army[x]-1-o.army[y];for(int d=0;d<4;++d){int z=g_.neighbor(y,d);if(z>=0&&z!=x&&o.owner[z]==2&&o.army[z]>=remaining)return false;}return true;}
 bool safe_step(const Observation&o,int x,int y)const{if(y<0||!g_.passable[y])return false;if(o.owner[y]==2)return safe_attack(o,x,y);for(int d=0;d<4;++d){int z=g_.neighbor(y,d);if(z>=0&&o.owner[z]==2&&o.army[z]>=o.army[x]-1)return false;}return true;}
 int tactical_next(const Observation&o,int x,int target)const{int best=-1,bd=INF;for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(safe_step(o,x,y)&&g_.dist[y][target]<bd)best=y,bd=g_.dist[y][target];}return best;}
 void reconcile(const Observation&o){if(pending_packet_){auto it=packets_.find(pending_packet_);if(it!=packets_.end()&&pending_to_>=0&&o.owner[pending_to_]==1){Packet&p=it->second;if(p.cell>=0&&packet_at_[p.cell]==p.id)packet_at_[p.cell]=0;p.cell=pending_to_;p.army=o.army[p.cell];p.path.push_back(p.cell);while(p.path.size()>12)p.path.pop_front();packet_at_[p.cell]=p.id;}else if(it!=packets_.end())packets_.erase(it);}pending_packet_=0;pending_to_=-1;for(auto it=packets_.begin();it!=packets_.end();)if(o.owner[it->second.cell]!=1)it=packets_.erase(it);else{it->second.army=o.army[it->second.cell];++it;}}
 const Packet* packet_for(int x)const{long id=x>=0&&x<n_?packet_at_[x]:0;auto it=packets_.find(id);return it==packets_.end()?nullptr:&it->second;}
 void commit_packet(const Observation&o,const Candidate&q){if(q.from<0||q.to<0)return;long id=packet_at_[q.from];Packet*p=nullptr;if(id&&packets_.count(id))p=&packets_[id];if(!p){Packet z;z.id=next_packet_++;z.cell=q.from;z.army=o.army[q.from];z.path.push_back(q.from);packets_[z.id]=z;packet_at_[q.from]=z.id;p=&packets_[z.id];}if(p->target!=q.target||p->front_id!=q.front_id||p->role!=q.role){p->target=q.target;p->front_id=q.front_id;p->role=q.role;p->assigned_turn=o.turn;p->assignment_reason=q.reason;p->idle=0;++objective_changes_;}if(p->event_version!=event_){++allowed_reversals_;p->event_version=event_;}pending_packet_=p->id;pending_to_=q.to;}
 bool history_cycle(const Candidate&q)const{if(q.from<0||q.to<0)return false;for(auto it=actions_.rbegin();it!=actions_.rend();++it){if(it->event!=event_)break;if(it->from==q.to&&it->to==q.from)return true;}return false;}
 bool packet_route_ok(const Candidate&q)const{auto p=packet_for(q.from);if(!p||q.target<0)return true;return route_allowed(*p,q.to,g_.dist[q.to][q.target],g_.dist[q.from][q.target],event_,q.reason);}
 Candidate strategic_pick(std::vector<Candidate>c,const std::array<double,5>&share,bool immediate){std::vector<Candidate>hard;for(auto&q:c)if(q.tier<=1)hard.push_back(q);if(!hard.empty())return schedule(hard);for(int i=1;i<5;++i)credit_[i]+=share[i];std::array<bool,5>available{};for(auto&q:c)available[(int)q.action_class]=true;int cls=-1;if(!immediate&&available[(int)ActionClass::EXPANSION]&&expansion_wait_>=4)cls=(int)ActionClass::EXPANSION;else for(int i=1;i<5;++i)if(available[i]&&(cls<0||credit_[i]>credit_[cls]))cls=i;if(cls<0)return {};Candidate best;bool have=false;for(auto&q:c)if((int)q.action_class==cls&&(!have||std::tuple(q.tier,-q.utility,q.from,q.to)<std::tuple(best.tier,-best.utility,best.from,best.to)))best=q,have=true;if(have){credit_[cls]-=1;++class_actions_[cls];}return best;}
 Candidate productive_fallback(const Observation&o,int sink){std::vector<Candidate>enemy,neutral,persistent,rear,consolidate,explore;bool movable=false,legal=false,safe=false,blocked=false;for(int x=0;x<n_;++x)if(source(o,x)){movable=true;for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y<0||!g_.passable[y])continue;legal=true;if(!safe_step(o,x,y))continue;safe=true;Candidate q{4,x,y,0,0,Reason::SEARCH_PROGRESS,false,ActionClass::LOGISTICS,y,-1,PacketRole::FREE_SURPLUS_RELOCATION};if(history_cycle(q)){blocked=true;continue;}if(o.owner[y]==2){q.utility=(o.army[x]-o.army[y])*20+g_.degree(y);q.reason=Reason::OPPONENT_EXPLOIT;q.action_class=ActionClass::OFFENSE;q.role=PacketRole::COUNTERATTACK;enemy.push_back(q);continue;}if(o.owner[y]==0&&o.army[x]-1>o.army[y]){q.utility=120-o.army[y]*15+g_.degree(y)*4+(o.type[y]==3?50:0);q.action_class=ActionClass::EXPANSION;q.role=PacketRole::EXPANSION;neutral.push_back(q);continue;}auto p=packet_for(x);if(p&&p->target>=0&&g_.dist[y][p->target]<g_.dist[x][p->target]){q.utility=1000-g_.dist[y][p->target];q.target=p->target;q.reason=p->assignment_reason;q.role=p->role;persistent.push_back(q);continue;}if(o.owner[y]==1){int edge=std::min({x/w_,h_-1-x/w_,x%w_,w_-1-x%w_});if(sink>=0&&g_.dist[y][sink]<g_.dist[x][sink]){q.utility=o.army[x]+(edge<=1?100:0);q.target=sink;q.reason=Reason::REAR_EVACUATION;rear.push_back(q);}else if(o.army[y]>o.army[x]&&g_.degree(y)>=g_.degree(x)){q.utility=o.army[y]-o.army[x];consolidate.push_back(q);}}else if(o.owner[y]<0){q.utility=g_.degree(y)*10; q.action_class=ActionClass::SEARCH;q.role=PacketRole::SEARCH;explore.push_back(q);}}}auto pick=[](std::vector<Candidate>&v){return schedule(v);};for(auto*v:{&enemy,&neutral,&persistent,&rear,&consolidate,&explore})if(!v->empty()){++pass_stats_.replaced;return pick(*v);}if(!movable)++pass_stats_.no_movable;else if(!legal)++pass_stats_.no_legal;else if(!safe)++pass_stats_.no_safe;else if(blocked)++pass_stats_.cycle_blocked;else ++pass_stats_.other;return {};}
 void count_action(const Observation&o,const Candidate&q,const Action&a){if(a.kind==1){++stats_.passes;return;}if(q.kind==2){++stats_.castle;return;}if(q.action_class==ActionClass::EXPANSION){++stats_.expansion;if(o.owner[q.to]==0)++stats_.neutral;}if(q.action_class==ActionClass::OFFENSE){++stats_.enemy;}if(q.reason==Reason::WAR_MOBILIZATION)++stats_.war;if(q.reason==Reason::REAR_EVACUATION)++stats_.rear;if(q.action_class==ActionClass::SEARCH)++stats_.search;if(q.reason==Reason::GENERAL_EMERGENCY)++stats_.defense;}
 Action act(const Observation&o){auto begin=std::chrono::steady_clock::now();if(g_.passable.empty())init(o);else reconcile(o);
  bool enemy_seen=false,meaningful=false,immediate=false;int largest=-1,largest_army=0;std::vector<std::pair<int,int>>contacts,tracked;std::vector<int>packet_sizes;
  for(int x=0;x<n_;++x){if(o.owner[x]==2){enemy_seen=true;if(o.type[x]==4&&!belief_.confirmed()){belief_.confirm(x);++event_;}bool moving=moved_enemy(o,x),interaction=enemy_adjacent_ours(o,x);int eta=general_>=0?g_.dist[x][general_]:INF;bool lethal_now=general_>=0&&eta==1&&(o.turn>=800||o.army[x]-1>o.army[general_]);bool threat=general_>=0&&(lethal_now||(eta<=2&&o.army[x]>=std::max(4,o.army[general_]/2))||(moving&&eta<=5&&o.army[x]>=6));if(moving||interaction||threat){meaningful=true;contacts.push_back({x,o.army[x]});}if(moving||o.army[x]>=6){tracked.push_back({x,o.army[x]});packet_sizes.push_back(o.army[x]);if(o.army[x]>largest_army)largest=x,largest_army=o.army[x];}if(threat)immediate=true;}if(o.type[x]>=0&&o.owner[x]!=2)belief_.eliminate(x);}
  auto changes=fronts_.update(g_,o.turn,contacts,general_);stale_closures_+=changes.closed;if(changes.added||changes.closed)++event_;max_fronts_=std::max(max_fronts_,fronts_.active_count());bool confirmed_war=fronts_.active_count()>0&&meaningful;if(meaningful&&meaningful_contact_turn_<0){meaningful_contact_turn_=o.turn;++event_;}
  land_hist_.push_back(o.my_land);opp_land_hist_.push_back(o.opp_land);opp_army_hist_.push_back(o.opp_army);auto slope=[](const std::vector<int>&v,int w){int n=v.size(),d=std::min(w,n-1);return d>0?double(v.back()-v[n-1-d])/d:0.;};OpponentEvidence ev;ev.turn=o.turn;ev.samples=tracked.size();ev.land_velocity=(slope(opp_land_hist_,5)+slope(opp_land_hist_,20))/2;ev.army_velocity=(slope(opp_army_hist_,10)+slope(opp_army_hist_,50))/2;ev.fronts=fronts_.active_count();if(!packet_sizes.empty()){std::sort(packet_sizes.begin(),packet_sizes.end());ev.median_packet=packet_sizes[packet_sizes.size()/2];ev.concentration=o.opp_army?double(packet_sizes.back())/o.opp_army:0;ev.activity=std::min(1.,tracked.size()/4.);ev.closing=largest>=0?std::max(0,10-g_.dist[largest][general_])/10.:0;}for(int x=0;x<n_;++x)ev.castles+=(o.owner[x]==2&&o.type[x]==3);opponent_.update(ev);auto adapt=opponent_.adaptation();
  int gap=o.opp_land-o.my_land;auto old=production_;if(production_==ProductionState::SEVERE_DEFICIT)production_=gap<10&&slope(land_hist_,10)>.1?ProductionState::SOFT_DEFICIT:production_;else if(gap>18)production_=ProductionState::SEVERE_DEFICIT;else if(gap>8)production_=ProductionState::SOFT_DEFICIT;else production_=ProductionState::HEALTHY;if(old!=production_)++event_;
  for(int i=0;i<2;++i){int s=i?castles_.c2:castles_.c1;if(s>=0&&o.owner[s]==1&&o.type[s]==3){castle_state_[i]=CastleState::BUILT;if(castle_build_[i]<0)castle_build_[i]=o.turn;}}bool own1=castles_.c1>=0&&o.owner[castles_.c1]==1,own2=castles_.c2>=0&&o.owner[castles_.c2]==1;auto f1=castle_state_[0]==CastleState::BUILT?FundingForecast{}:forecast(o.turn,150,castles_.cost1,own1?o.army[castles_.c1]:0,feeders(o,castles_.c1),own1);auto f2=castle_state_[1]==CastleState::BUILT?FundingForecast{}:forecast(o.turn,250,castles_.cost2,own2?o.army[castles_.c2]:0,feeders(o,castles_.c2),own2);castle_latest_={f1.latest_start,f2.latest_start};castle_actions_={f1.required_actions,f2.required_actions};for(int i=0;i<2;++i)if((i?f2.must_fund:f1.must_fund)&&castle_start_[i]<0)castle_start_[i]=o.turn;if(o.turn>150&&castle_build_[0]<0)castle_miss_=f1.capacity<f1.required?"c1_insufficient_army":f1.required_actions>f1.turns?"c1_action_infeasible":"c1_unavailable";else if(o.turn>250&&castle_build_[1]<0)castle_miss_=f2.capacity<f2.required?"c2_insufficient_army":f2.required_actions>f2.turns?"c2_action_infeasible":"c2_unavailable";int c1reserve=(f1.feasible&&f1.must_fund)?f1.required:0;int c2reserve=(castle_state_[0]==CastleState::BUILT&&f2.feasible&&f2.must_fund)?f2.required:0;auto b=budget(o.my_army,general_>=0?o.army[general_]:0,c1reserve,c2reserve,confirmed_war,adapt.attack);if(production_==ProductionState::SEVERE_DEFICIT){b.expansion=std::max(b.expansion,b.free+b.search+b.war/2);b.search=0;b.war/=2;}b.expansion=int(b.expansion*std::max(.5,adapt.expansion/.3));b.search=int(b.search*std::max(.5,adapt.search/.25));sum_c1_+=c1reserve;sum_c2_+=c2reserve;sum_war_+=b.war;sum_expansion_+=b.expansion;sum_search_+=b.search;sum_free_+=b.free;++budget_samples_;
  std::vector<Candidate>c;for(int x=0;x<n_;++x)if(source(o,x))for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y<0||!g_.passable[y])continue;if(o.type[y]==4&&o.owner[y]==2&&(o.turn>=800||safe_attack(o,x,y)))c.push_back({0,x,y,0,10000,Reason::TERMINAL_CAPTURE,false,ActionClass::HARD,y,-1,PacketRole::ATTACK});else if(safe_attack(o,x,y))c.push_back({1,x,y,0,double((o.army[x]-o.army[y])*10+g_.degree(y)*3),Reason::OPPONENT_EXPLOIT,false,ActionClass::OFFENSE,y,-1,PacketRole::ATTACK});}
  if(immediate)for(int x=0;x<n_;++x)if(source(o,x)){int y=tactical_next(o,x,general_);if(y>=0&&o.owner[y]==1)c.push_back({0,x,y,0,double(o.army[x]),Reason::GENERAL_EMERGENCY,false,ActionClass::HARD,general_,-1,PacketRole::GENERAL_DEFENSE});}
  for(auto [site,f,index]:{std::tuple{castles_.c1,f1,0},std::tuple{castles_.c2,f2,1}})if(site>=0&&castle_state_[index]!=CastleState::BUILT&&(index==0||castle_state_[0]==CastleState::BUILT)){int cost=index?castles_.cost2:castles_.cost1;if(o.owner[site]==1&&o.type[site]==1&&o.army[site]>=cost)c.push_back({1,site,site,2,100,Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});else if(f.must_fund)for(int x=0;x<n_;++x)if(source(o,x)){int y=tactical_next(o,x,site);if(y>=0)c.push_back({1,x,y,0,double(o.army[x])/std::max(1,g_.dist[x][site]),Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});}}
  int until=50-o.turn%50;for(int x=0;x<n_;++x)if(source(o,x))for(int d=0;d<4;++d){int y=g_.neighbor(x,d);if(y>=0&&g_.passable[y]&&o.owner[y]==0&&o.army[x]-1>o.army[y]&&o.army[y]+1<=std::max({2,b.expansion,o.my_army/4})){double u=100-o.army[y]*12+g_.degree(y)*5+(until<=8?30:0);c.push_back({2,x,y,0,u,until<=8?Reason::PRODUCTION_TICK:Reason::SEARCH_PROGRESS,false,ActionClass::EXPANSION,y,-1,PacketRole::EXPANSION});}}
  const Front*front=fronts_.primary();int sink=belief_.confirmed()?belief_.confirmed_cell():(front?front->anchor:belief_.top());for(int x=0;x<n_;++x)if(source(o,x)){int surplus=o.army[x]-reserve(o,x);if(surplus<=0)continue;int edge=std::min({x/w_,h_-1-x/w_,x%w_,w_-1-x%w_});bool rear=edge<=1||g_.degree(x)<=1;int target=sink==x?general_:sink,y=target>=0?tactical_next(o,x,target):-1;if(y<0)continue;if(confirmed_war&&b.war>0)c.push_back({2,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::WAR_MOBILIZATION,false,ActionClass::LOGISTICS,target,front?front->id:-1,PacketRole::FRONT});else if(rear&&b.free+b.search>0)c.push_back({2,x,y,0,double(surplus),Reason::REAR_EVACUATION,false,ActionClass::LOGISTICS,target,-1,PacketRole::FREE_SURPLUS_RELOCATION});else if(!enemy_seen&&b.search>0)c.push_back({3,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::SEARCH_PROGRESS,false,ActionClass::SEARCH,target,-1,PacketRole::SEARCH});}
  std::vector<Candidate>filtered;for(auto&q:c){bool reject=history_cycle(q)||!packet_route_ok(q);if(reject&&q.tier>1){++candidate_reject_;continue;}filtered.push_back(q);}bool expansion_available=std::any_of(filtered.begin(),filtered.end(),[](auto&q){return q.action_class==ActionClass::EXPANSION;});std::array<double,5>share{{0,confirmed_war?.30:.12,production_==ProductionState::SEVERE_DEFICIT?.62:production_==ProductionState::SOFT_DEFICIT?.45:.35,!enemy_seen?.20:.08,confirmed_war?.22:.15}};double total=share[1]+share[2]+share[3]+share[4];for(int i=1;i<5;++i)share[i]/=total;Candidate q=strategic_pick(filtered,share,immediate);if(expansion_available&&q.action_class!=ActionClass::EXPANSION&&!immediate)++expansion_wait_;else if(q.action_class==ActionClass::EXPANSION)expansion_wait_=0;
  if(q.from<0){++pass_stats_.no_strategic_candidate;q=productive_fallback(o,sink);}Action a=pass();if(q.kind==2)a={2,q.from/w_,q.from%w_,0,0};else if(q.from>=0)a=move(q.from,q.to,q.split);if(a.kind==0){commit_packet(o,q);if(!actions_.empty()&&actions_.back().from==q.to&&actions_.back().to==q.from)++executed_reverse_;bool prior_cycle=false;for(auto&m:actions_)prior_cycle|=m.from==q.to&&m.to==q.from&&m.event==event_;if(prior_cycle)++executed_cycle_;actions_.push_back({q.from,q.to,event_,q.action_class});while(actions_.size()>12)actions_.pop_front();}count_action(o,q,a);last_owner_=o.owner;last_army_=o.army;for(int t:{50,100,150,200,250,300,400,600,800})if(o.turn>=t&&!land_snapshots_.count(t))land_snapshots_[t]=o.my_land;
  double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();times_.push_back(ms);return a;}
 void report(){if(times_.empty())return;std::sort(times_.begin(),times_.end());auto pct=[&](double q){return times_[std::min(times_.size()-1,(size_t)std::ceil(q*times_.size())-1)];};double n=std::max<long>(1,budget_samples_);std::fprintf(stderr,"[v35_castle_deadline] c1_site=%d c1_cost=%d c1_latest_start=%d c1_required_actions=%d c1_start_turn=%d c1_build_turn=%d c2_site=%d c2_cost=%d c2_latest_start=%d c2_required_actions=%d c2_start_turn=%d c2_build_turn=%d miss_reason=%s\n",castles_.c1,castles_.cost1,castle_latest_[0],castle_actions_[0],castle_start_[0],castle_build_[0],castles_.c2,castles_.cost2,castle_latest_[1],castle_actions_[1],castle_start_[1],castle_build_[1],castle_miss_.c_str());std::fprintf(stderr,"[v35_actions] expansion=%ld neutral=%ld enemy=%ld war=%ld rear=%ld search=%ld castle=%ld defense=%ld pass=%ld\n",stats_.expansion,stats_.neutral,stats_.enemy,stats_.war,stats_.rear,stats_.search,stats_.castle,stats_.defense,stats_.passes);std::fprintf(stderr,"[v35_pass] pass_no_movable=%ld pass_no_legal=%ld pass_no_safe=%ld pass_cycle_blocked=%ld pass_no_strategic_candidate=%ld pass_other=%ld avoidable_pass_replaced=%ld\n",pass_stats_.no_movable,pass_stats_.no_legal,pass_stats_.no_safe,pass_stats_.cycle_blocked,pass_stats_.no_strategic_candidate,pass_stats_.other,pass_stats_.replaced);std::fprintf(stderr,"[v35_land]");for(auto [t,l]:land_snapshots_)std::fprintf(stderr," %d:%d",t,l);std::fputc('\n',stderr);std::fprintf(stderr,"[v35_budget] c1=%.2f c2=%.2f war=%.2f expansion=%.2f search=%.2f free=%.2f\n",sum_c1_/n,sum_c2_/n,sum_war_/n,sum_expansion_/n,sum_search_/n,sum_free_/n);std::fprintf(stderr,"[v35_front] meaningful_contact=%d max_active=%d closures=%d\n",meaningful_contact_turn_,max_fronts_,stale_closures_);std::fprintf(stderr,"[v35_cycles] candidate_route_rejections=%ld selected_preventions=%ld executed_reverse=%ld executed_short=%ld\n",candidate_reject_,selected_cycle_prevent_,executed_reverse_,executed_cycle_);std::fprintf(stderr,"[v35_logistics] packets=%zu objective_changes=%ld allowed_reversals=%ld\n",packets_.size(),objective_changes_,allowed_reversals_);std::fprintf(stderr,"[v35_timing] p50=%.3f p95=%.3f p99=%.3f max=%.3f\n",pct(.5),pct(.95),pct(.99),times_.back());}
public:
 Agent(int p,int h,int w):player_(p),h_(h),w_(w),n_(h*w){}Action decide(const Observation&o){try{return act(o);}catch(...){return pass();}}
 size_t packet_count()const{return packets_.size();}long objective_changes()const{return objective_changes_;}int active_fronts()const{return fronts_.active_count();}int meaningful_contact_turn()const{return meaningful_contact_turn_;}ProductionState production_state()const{return production_;}bool enemy_general_confirmed()const{return belief_.confirmed();}int enemy_general_cell()const{return belief_.confirmed_cell();}const auto& confidence()const{return opponent_.confidence();}const ActionStats& action_stats()const{return stats_;}~Agent(){report();}
};
static bool grid(std::vector<int>&g){for(int&x:g)if(std::scanf("%d",&x)!=1)return false;return true;}
#ifndef V35_AGENT_TEST
int main(){int p,h,w;if(std::scanf("%d %d %d",&p,&h,&w)!=3)return 0;Agent a(p,h,w);Observation o;o.type.resize(h*w);o.owner.resize(h*w);o.army.resize(h*w);while(std::scanf("%d %d %d %d %d",&o.turn,&o.my_land,&o.my_army,&o.opp_land,&o.opp_army)==5){if(!grid(o.type)||!grid(o.owner)||!grid(o.army))break;auto x=a.decide(o);std::printf("%d %d %d %d %d\n",x.kind,x.row,x.col,x.dir,x.split);std::fflush(stdout);}return 0;}
#endif
