from pathlib import Path

MAIN = Path('competition/agents/juraj_v35_cpp/main.cpp')
CORE = Path('competition/agents/juraj_v35_cpp/core.hpp')
TEST_CORE = Path('competition/agents/juraj_v35_cpp/test_core.cpp')
TEST_SH = Path('competition/agents/juraj_v35_cpp/test.sh')
TEST_STALL = Path('competition/agents/juraj_v35_cpp/test_stall_hardening.cpp')


def replace_once(text, old, new, label):
    if new in text:
        print(f'{label}: already applied')
        return text
    n = text.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected exactly one old block, found {n}')
    print(f'{label}: applied')
    return text.replace(old, new, 1)

s = CORE.read_text()
old = '''inline bool route_allowed(const Packet&p,int dest,int new_distance,int old_distance,int event_version,Reason reason){bool changed=event_version!=p.event_version&&reason!=Reason::NONE;if(!changed&&new_distance>old_distance)return false;if(!changed&&p.path.size()>=2&&dest==p.path[p.path.size()-2])return false;if(!changed&&p.path.size()>=3&&dest==p.path[p.path.size()-3])return false;if(!changed&&p.path.size()>=4&&dest==p.path[p.path.size()-4])return false;return true;}'''
new = '''inline bool route_allowed(const Packet&p,int dest,int new_distance,int old_distance,int event_version,Reason reason){bool emergency=reason==Reason::GENERAL_EMERGENCY||reason==Reason::TERMINAL_CAPTURE;bool mobile=p.role==PacketRole::EXPANSION||p.role==PacketRole::SEARCH||p.role==PacketRole::FRONT||p.role==PacketRole::ATTACK||p.role==PacketRole::COUNTERATTACK;if(!emergency&&mobile&&std::find(p.path.begin(),p.path.end(),dest)!=p.path.end())return false;bool changed=event_version!=p.event_version&&reason!=Reason::NONE;if(!emergency&&!changed&&new_distance>old_distance)return false;if(!emergency&&!changed&&p.path.size()>=2&&dest==p.path[p.path.size()-2])return false;if(!emergency&&!changed&&p.path.size()>=3&&dest==p.path[p.path.size()-3])return false;if(!emergency&&!changed&&p.path.size()>=4&&dest==p.path[p.path.size()-4])return false;return true;}'''
s = replace_once(s, old, new, 'hard packet path tabu')
CORE.write_text(s)

s = MAIN.read_text()
old = ''' std::array<int,9> sector_target_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_first_touch_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_last_progress_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_owned_max_{{0,0,0,0,0,0,0,0,0}},sector_passable_{{0,0,0,0,0,0,0,0,0}};std::array<std::vector<int>,9> sector_backbone_;int general_sector_=-1,sector_primary_=-1,sector_secondary_=-1;long sector_probe_moves_=0,sector_forced_moves_=0;'''
new = ''' std::array<int,9> sector_target_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_first_touch_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_last_progress_{{-1,-1,-1,-1,-1,-1,-1,-1,-1}},sector_owned_max_{{0,0,0,0,0,0,0,0,0}},sector_passable_{{0,0,0,0,0,0,0,0,0}};std::array<std::vector<int>,9> sector_backbone_;int general_sector_=-1,sector_primary_=-1,sector_secondary_=-1;long sector_probe_moves_=0,sector_forced_moves_=0,expansion_emergency_ticks_=0,breakout_moves_=0,short_cycle_blocks_=0;'''
s = replace_once(s, old, new, 'stall/cycle telemetry fields')
s = replace_once(s, 'if(belief_.confirmed()||general_<0||o.turn<80)return out;', 'if(belief_.confirmed()||general_<0||o.turn<20)return out;', 'early sector probing')
old = '''bool sector_probe_forced(const Observation&o,int s)const{if(s<0)return false;int reachable=search_reachable_count(),touched=sector_touched_count();if(o.turn>=550&&(touched<reachable||!sector_swept(s)))return true;if(o.turn>=400&&touched<std::min(reachable,7)&&sector_first_touch_[s]<0)return true;if(o.turn>=250&&touched<std::min(reachable,5)&&sector_first_touch_[s]<0)return true;return false;}'''
new = '''bool sector_probe_forced(const Observation&o,int s)const{if(s<0)return false;int reachable=search_reachable_count(),touched=sector_touched_count();if(o.turn>=20&&o.turn<=220&&(o.my_land<=10||o.opp_land-o.my_land>=10))return true;if(o.turn>=550&&(touched<reachable||!sector_swept(s)))return true;if(o.turn>=400&&touched<std::min(reachable,7)&&sector_first_touch_[s]<0)return true;if(o.turn>=250&&touched<std::min(reachable,5)&&sector_first_touch_[s]<0)return true;return false;}'''
s = replace_once(s, old, new, 'low-land forced sector probe')
old = '''Candidate sector_probe_candidate(const Observation&o,int s,bool forced,int avoid_from)const{int target=sector_goal(o,s);if(target<0)return {};auto make=[&](int x){if(x<0||x==avoid_from||!source(o,x)||x==general_||(picker_.active&&x==picker_.cell)||x==castles_.c1||x==castles_.c2)return Candidate{};int surplus=o.army[x]-reserve(o,x);if(surplus<(forced?2:4))return Candidate{};int y=tactical_next(o,x,target);if(y<0)return Candidate{};double u=(forced?4200.:1400.)+surplus*10.-g_.dist[x][target]*5.+(o.owner[y]!=1?120.:0);return Candidate{forced?2:3,x,y,0,u,Reason::SEARCH_PROGRESS,false,ActionClass::SEARCH,target,-1,PacketRole::SEARCH};};Candidate best;bool have=false;for(auto&kv:packets_){const Packet&p=kv.second;if(p.role!=PacketRole::SEARCH||sector_of(p.target)!=s)continue;Candidate q=make(p.cell);if(q.from>=0&&(!have||q.utility>best.utility))best=q,have=true;}if(have)return best;for(int x=0;x<n_;++x){Candidate q=make(x);if(q.from>=0&&(!have||q.utility>best.utility))best=q,have=true;}return have?best:Candidate{};}'''
new = '''Candidate sector_probe_candidate(const Observation&o,int s,bool forced,int avoid_from)const{int target=sector_goal(o,s);if(target<0)return {};auto make=[&](int x){if(x<0||x==avoid_from||!source(o,x)||(picker_.active&&x==picker_.cell)||x==castles_.c1||x==castles_.c2)return Candidate{};int surplus=o.army[x]-reserve(o,x);if(surplus<(forced?2:4))return Candidate{};int y=tactical_next(o,x,target);if(y<0)return Candidate{};double u=(forced?4200.:1400.)+surplus*10.-g_.dist[x][target]*5.+(o.owner[y]!=1?120.:0)+(x==general_?80.:0);return Candidate{forced?2:3,x,y,0,u,Reason::SEARCH_PROGRESS,x==general_,ActionClass::SEARCH,target,-1,PacketRole::SEARCH};};Candidate best;bool have=false;for(auto&kv:packets_){const Packet&p=kv.second;if(p.role!=PacketRole::SEARCH||sector_of(p.target)!=s)continue;Candidate q=make(p.cell);if(q.from>=0&&(!have||q.utility>best.utility))best=q,have=true;}if(have)return best;for(int x=0;x<n_;++x){Candidate q=make(x);if(q.from>=0&&(!have||q.utility>best.utility))best=q,have=true;}return have?best:Candidate{};}'''
s = replace_once(s, old, new, 'general-seeded sector probes')
anchor = new
insert = new + '''\n Candidate forced_breakout_candidate(const Observation&o)const{Candidate best;bool have=false;for(int x=0;x<n_;++x)if(source(o,x)){if((picker_.active&&x==picker_.cell)||x==castles_.c1||x==castles_.c2)continue;int surplus=o.army[x]-reserve(o,x);if(surplus<2)continue;int target=-1,bd=INF;for(int z=0;z<n_;++z)if(g_.passable[z]&&o.owner[z]!=1&&o.owner[z]!=2&&g_.dist[x][z]<bd){bd=g_.dist[x][z];target=z;}if(target<0||bd>=INF)continue;int y=tactical_next(o,x,target);if(y<0)continue;double u=6000.+surplus*20.-bd*8.+(o.owner[y]!=1?500.:0)+(x==general_?80.:0);ActionClass cls=o.owner[y]==0?ActionClass::EXPANSION:ActionClass::SEARCH;Candidate q{2,x,y,0,u,Reason::PRODUCTION_EMERGENCY,x==general_,cls,target,-1,PacketRole::SEARCH};if(!have||std::tuple(-q.utility,q.from,q.to)<std::tuple(-best.utility,best.from,best.to))best=q,have=true;}return have?best:Candidate{};}'''
if 'Candidate forced_breakout_candidate' not in s:
    if s.count(anchor)!=1: raise SystemExit('forced breakout candidate anchor mismatch')
    s=s.replace(anchor,insert,1);print('forced breakout candidate: applied')
else: print('forced breakout candidate: already applied')
s = replace_once(s, 'while(p.path.size()>12)p.path.pop_front();', 'while(p.path.size()>32)p.path.pop_front();', 'longer packet route history')
old = '''bool history_cycle(const Candidate&q)const{if(q.from<0||q.to<0)return false;for(auto it=actions_.rbegin();it!=actions_.rend();++it){if(it->event!=event_)break;if(it->from==q.to&&it->to==q.from)return true;}return false;}'''
new = '''bool history_cycle(const Candidate&q)const{if(q.from<0||q.to<0)return false;int seen=0;for(auto it=actions_.rbegin();it!=actions_.rend()&&seen<4;++it,++seen)if((it->from==q.to&&it->to==q.from)||(it->from==q.from&&it->to==q.to))return true;return false;}'''
s = replace_once(s, old, new, 'event-independent four-move cycle guard')
s = replace_once(s, 'if(production_==ProductionState::SEVERE_DEFICIT){b.expansion=std::max(b.expansion,b.free+b.search+b.war/2);b.search=0;b.war/=2;}', 'if(production_==ProductionState::SEVERE_DEFICIT){b.expansion=std::max(b.expansion,b.free+b.search+b.war/2);b.search=std::max(b.search,std::max(2,o.my_army/12));b.war/=2;}', 'preserve search under severe land deficit')
old = '''  auto probe_sectors=choose_probe_sectors(o);sector_primary_=probe_sectors[0];sector_secondary_=probe_sectors[1];int probe_avoid=-1;for(int k=0;k<2;++k){int sec=probe_sectors[k];if(sec<0||belief_.confirmed()||b.search<=0)continue;bool forced=sector_probe_forced(o,sec);Candidate pq=sector_probe_candidate(o,sec,forced,probe_avoid);if(pq.from>=0){c.push_back(pq);probe_avoid=pq.from;}}'''
new = '''  int stall_back=std::min<int>(8,std::max<int>(0,(int)land_hist_.size()-1));bool land_stalled=stall_back>=4&&o.my_land<=land_hist_[land_hist_.size()-1-stall_back]+1;bool low_land_pressure=o.turn>=20&&o.turn<=220&&(o.my_land<=10||gap>=10);bool expansion_emergency=low_land_pressure&&(o.my_land<=8||land_stalled);if(expansion_emergency)++expansion_emergency_ticks_;Candidate breakout=expansion_emergency?forced_breakout_candidate(o):Candidate{};if(breakout.from>=0)c.push_back(breakout);\n  auto probe_sectors=choose_probe_sectors(o);sector_primary_=probe_sectors[0];sector_secondary_=probe_sectors[1];int probe_avoid=-1;for(int k=0;k<2;++k){int sec=probe_sectors[k];if(sec<0||belief_.confirmed()||b.search<=0)continue;bool forced=sector_probe_forced(o,sec);Candidate pq=sector_probe_candidate(o,sec,forced,probe_avoid);if(pq.from>=0){c.push_back(pq);probe_avoid=pq.from;}}'''
s = replace_once(s, old, new, 'explicit expansion emergency')
s = replace_once(s, 'else if(!enemy_seen&&b.search>0)c.push_back({3,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::SEARCH_PROGRESS,false,ActionClass::SEARCH,target,-1,PacketRole::SEARCH});', 'else if((!enemy_seen||expansion_emergency)&&b.search>0)c.push_back({3,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::SEARCH_PROGRESS,false,ActionClass::SEARCH,target,-1,PacketRole::SEARCH});', 'search despite noncritical sighting during stall')
s = replace_once(s, 'bool severe=o.turn>=60&&o.turn<=180&&o.my_land<=10&&stall_window_.size()>=20&&o.my_land-window_min_land<=2&&window_pass>=5;', 'bool severe=o.turn>=60&&o.turn<=180&&o.my_land<=10&&stall_window_.size()>=20&&o.my_land-window_min_land<=2&&(window_pass>=5||land_stalled);', 'stall recovery detects movement loops')
old = '''std::vector<Candidate>filtered;for(auto&q:c){bool reserved=picker_.active&&q.from==picker_.cell&&q.role!=PacketRole::EDGE_PICKER&&q.reason!=Reason::GENERAL_EMERGENCY&&q.reason!=Reason::TERMINAL_CAPTURE;if(reserved){++picker_source_guard_rejects_;continue;}bool reject=history_cycle(q)||!packet_route_ok(q);if(reject&&q.tier>1&&q.role!=PacketRole::EDGE_PICKER){++candidate_reject_;continue;}filtered.push_back(q);}bool expansion_available=std::any_of(filtered.begin(),filtered.end(),[](auto&q){return q.action_class==ActionClass::EXPANSION;});bool picker_available=std::any_of(filtered.begin(),filtered.end(),[](auto&q){return q.role==PacketRole::EDGE_PICKER;});auto critical=[](const Candidate&q){return q.tier<=1&&(q.reason==Reason::TERMINAL_CAPTURE||q.reason==Reason::GENERAL_EMERGENCY||q.reason==Reason::CASTLE_DEADLINE);};bool critical_available=std::any_of(filtered.begin(),filtered.end(),critical);bool coverage_force_available=std::any_of(filtered.begin(),filtered.end(),[](const Candidate&z){return z.role==PacketRole::SEARCH&&z.reason==Reason::SEARCH_PROGRESS&&z.tier==2;});'''
new = '''std::vector<Candidate>filtered;for(auto&q:c){bool reserved=picker_.active&&q.from==picker_.cell&&q.role!=PacketRole::EDGE_PICKER&&q.reason!=Reason::GENERAL_EMERGENCY&&q.reason!=Reason::TERMINAL_CAPTURE;if(reserved){++picker_source_guard_rejects_;continue;}bool hist=history_cycle(q),route_bad=!packet_route_ok(q);if(hist&&q.tier>1&&q.role!=PacketRole::EDGE_PICKER)++short_cycle_blocks_;bool reject=hist||route_bad;if(reject&&q.tier>1&&q.role!=PacketRole::EDGE_PICKER){++candidate_reject_;continue;}filtered.push_back(q);}bool expansion_available=std::any_of(filtered.begin(),filtered.end(),[](auto&q){return q.action_class==ActionClass::EXPANSION;});bool picker_available=std::any_of(filtered.begin(),filtered.end(),[](auto&q){return q.role==PacketRole::EDGE_PICKER;});auto critical=[](const Candidate&q){return q.tier<=1&&(q.reason==Reason::TERMINAL_CAPTURE||q.reason==Reason::GENERAL_EMERGENCY||q.reason==Reason::CASTLE_DEADLINE);};bool critical_available=std::any_of(filtered.begin(),filtered.end(),critical);bool breakout_available=std::any_of(filtered.begin(),filtered.end(),[](const Candidate&z){return z.reason==Reason::PRODUCTION_EMERGENCY&&z.tier==2;});bool coverage_force_available=std::any_of(filtered.begin(),filtered.end(),[](const Candidate&z){return z.role==PacketRole::SEARCH&&z.reason==Reason::SEARCH_PROGRESS&&z.tier==2;});'''
s = replace_once(s, old, new, 'cycle telemetry and breakout availability')
old = '''Candidate q;if(picker_.active&&critical_available){std::vector<Candidate>hv;for(auto&z:filtered)if(critical(z))hv.push_back(z);q=schedule(hv);}else if(coverage_force_available&&((picker_.active&&o.turn%6==0)||(!picker_.active&&o.turn%4==0))){std::vector<Candidate>sv;for(auto&z:filtered)if(z.role==PacketRole::SEARCH&&z.reason==Reason::SEARCH_PROGRESS&&z.tier==2)sv.push_back(z);q=schedule(sv);}else if(picker_.active&&picker_available){std::vector<Candidate>pv;for(auto&z:filtered)if(z.role==PacketRole::EDGE_PICKER)pv.push_back(z);q=schedule(pv);}else q=strategic_pick(filtered,share,immediate);'''
new = '''Candidate q;if(critical_available){std::vector<Candidate>hv;for(auto&z:filtered)if(critical(z))hv.push_back(z);q=schedule(hv);}else if(expansion_emergency&&breakout_available){std::vector<Candidate>bv;for(auto&z:filtered)if(z.reason==Reason::PRODUCTION_EMERGENCY&&z.tier==2)bv.push_back(z);q=schedule(bv);}else if(expansion_emergency&&coverage_force_available){std::vector<Candidate>sv;for(auto&z:filtered)if(z.role==PacketRole::SEARCH&&z.reason==Reason::SEARCH_PROGRESS&&z.tier==2)sv.push_back(z);q=schedule(sv);}else if(coverage_force_available&&((picker_.active&&o.turn%6==0)||(!picker_.active&&o.turn%4==0))){std::vector<Candidate>sv;for(auto&z:filtered)if(z.role==PacketRole::SEARCH&&z.reason==Reason::SEARCH_PROGRESS&&z.tier==2)sv.push_back(z);q=schedule(sv);}else if(picker_.active&&picker_available){std::vector<Candidate>pv;for(auto&z:filtered)if(z.role==PacketRole::EDGE_PICKER)pv.push_back(z);q=schedule(pv);}else q=strategic_pick(filtered,share,immediate);'''
s = replace_once(s, old, new, 'hard low-land expansion scheduling')
s = replace_once(s, 'if(a.kind==0&&q.role==PacketRole::SEARCH){++sector_probe_moves_;if(q.tier==2)++sector_forced_moves_;}count_action(o,q,a);', 'if(a.kind==0&&q.role==PacketRole::SEARCH){++sector_probe_moves_;if(q.tier==2)++sector_forced_moves_;if(q.reason==Reason::PRODUCTION_EMERGENCY)++breakout_moves_;}count_action(o,q,a);', 'breakout move telemetry')
needle = '''std::fprintf(stderr,"[v36_search] reachable=%d touched=%d swept=%d primary=%d secondary=%d probe_moves=%ld forced_moves=%ld\\n",search_reachable_count(),sector_touched_count(),sector_swept_count(),sector_primary_,sector_secondary_,sector_probe_moves_,sector_forced_moves_);'''
rep = needle + '''std::fprintf(stderr,"[v36_stall] emergency_ticks=%ld breakout_moves=%ld short_cycle_blocks=%ld\\n",expansion_emergency_ticks_,breakout_moves_,short_cycle_blocks_);'''
if rep not in s:
    if s.count(needle)!=1: raise SystemExit('stall telemetry report anchor mismatch')
    s=s.replace(needle,rep,1);print('stall telemetry report: applied')
MAIN.write_text(s)

t = TEST_CORE.read_text()
needle = ''' // 9 a real strategic event permits reversal.\n assert(route_allowed(p,2,3,2,2,Reason::GENERAL_EMERGENCY));'''
rep = ''' // 9 noncritical event changes do NOT reopen visited cells.\n p.role=PacketRole::SEARCH;assert(!route_allowed(p,1,2,2,2,Reason::SEARCH_PROGRESS));\n // 10 a real general emergency may still override the tabu.\n assert(route_allowed(p,2,3,2,2,Reason::GENERAL_EMERGENCY));'''
t = replace_once(t, needle, rep, 'core no-revisit regression')
t = t.replace('v35 core: 20 behavioral checks passed','v35 core: 21 behavioral checks passed')
TEST_CORE.write_text(t)

TEST_STALL.write_text(r'''#define V35_AGENT_TEST
#include "main.cpp"
#include <algorithm>
#include <cassert>
#include <iostream>
static int src(const Action&a){return a.row*21+a.col;}static int dst(const Action&a){if(a.kind)return -1;static int dr[4]={-1,1,0,0},dc[4]={0,0,-1,1};return (a.row+dr[a.dir])*21+a.col+dc[a.dir];}
static void recalc(Observation&o){o.my_land=0;o.my_army=0;for(int z=0;z<441;++z)if(o.owner[z]==1){++o.my_land;o.my_army+=o.army[z];}}
static void apply(Observation&o,const Action&a){if(a.kind!=0){++o.turn;return;}int x=src(a),y=dst(a),have=o.army[x],moving=a.split?std::max(1,have/2):std::max(0,have-1);if(moving<=0){++o.turn;return;}o.army[x]-=moving;if(o.owner[y]==1)o.army[y]+=moving;else{int defend=std::max(0,o.army[y]);o.owner[y]=1;o.army[y]=std::max(1,moving-defend);if(o.type[y]<0)o.type[y]=1;}recalc(o);++o.turn;}
static Observation stalled(){Observation o;o.turn=61;o.type.assign(441,-1);o.owner.assign(441,-1);o.army.assign(441,0);int g=2*21+18;o.type[g]=4;o.owner[g]=1;o.army[g]=29;for(int z:{2*21+17,2*21+19,1*21+17,1*21+18,1*21+19,3*21+18}){o.type[z]=1;o.owner[z]=1;o.army[z]=1;}o.opp_land=29;o.opp_army=50;recalc(o);assert(o.my_land==7&&o.my_army==35);return o;}
int main(){Agent a(0,21,21);auto o=stalled();int initial=o.my_land,prev_from=-1,prev_to=-1,moves=0;for(int i=0;i<8&&o.my_land==initial;++i){auto q=a.decide(o);assert(q.kind==0);int f=src(q),t=dst(q);if(prev_from>=0)assert(!(f==prev_to&&t==prev_from));prev_from=f;prev_to=t;++moves;apply(o,q);}assert(moves>0);assert(o.my_land>initial);std::cout<<"v36 low-land breakout and anti-zigzag scenarios passed\n";}
''')
print('test_stall_hardening.cpp: written')
u=TEST_SH.read_text();block='''\ng++ -O2 -std=c++17 -Wall -Wextra -Wpedantic test_stall_hardening.cpp -o test_stall_hardening\n./test_stall_hardening\n'''
if 'test_stall_hardening.cpp' not in u:u+=block;TEST_SH.write_text(u);print('test.sh stall regression: applied')
print('V3.6 expansion/cycle hardening patch complete')
