#!/usr/bin/env python3
from pathlib import Path
root=Path(__file__).resolve().parents[1]
core=root/'competition/agents/juraj_v35_cpp/core.hpp'
main=root/'competition/agents/juraj_v35_cpp/main.cpp'
test=root/'competition/agents/juraj_v35_cpp/test_core.cpp'
testa=root/'competition/agents/juraj_v35_cpp/test_agent.cpp'

def repl(path,old,new,label):
    s=path.read_text()
    if new in s:
        print(label+': already applied'); return
    if old not in s:
        raise SystemExit(f'{label}: source pattern not found')
    path.write_text(s.replace(old,new,1)); print(label+': applied')

old="inline FundingForecast forecast(int turn,int deadline,int cost,int site_army,const std::vector<std::pair<int,int>>&feeders,bool site_owned=true,int safety_margin=5){FundingForecast f;f.required=std::max(0,cost-site_army);f.turns=std::max(0,deadline-turn);f.site_actions=site_owned?0:1;auto sorted=feeders;std::sort(sorted.begin(),sorted.end(),[](auto a,auto b){return std::tuple(a.second,-a.first)<std::tuple(b.second,-b.first);});for(auto [surplus,eta]:sorted)if(surplus>0){f.capacity+=surplus;f.transport_actions+=eta;if(f.capacity>=f.required)break;}f.required_actions=f.transport_actions+f.site_actions+f.build_actions;f.feasible=f.capacity>=f.required&&f.required_actions<=f.turns;f.latest_start=deadline-f.required_actions-safety_margin;f.slack=deadline-turn-f.required_actions;f.must_fund=f.feasible&&turn>=f.latest_start&&f.required>0;return f;}\nstruct Packet"
new="inline FundingForecast forecast(int turn,int deadline,int cost,int site_army,const std::vector<std::pair<int,int>>&feeders,bool site_owned=true,int safety_margin=5){FundingForecast f;f.required=std::max(0,cost-site_army);f.turns=std::max(0,deadline-turn);f.site_actions=site_owned?0:1;auto sorted=feeders;std::sort(sorted.begin(),sorted.end(),[](auto a,auto b){return std::tuple(a.second,-a.first)<std::tuple(b.second,-b.first);});for(auto [surplus,eta]:sorted)if(surplus>0){f.capacity+=surplus;f.transport_actions+=eta;if(f.capacity>=f.required)break;}f.required_actions=f.transport_actions+f.site_actions+f.build_actions;f.feasible=f.capacity>=f.required&&f.required_actions<=f.turns;f.latest_start=deadline-f.required_actions-safety_margin;f.slack=deadline-turn-f.required_actions;f.must_fund=f.feasible&&turn>=f.latest_start&&f.required>0;return f;}\ninline bool castle_funding_active(CastleState state,bool prerequisite,const FundingForecast&f,int started,int turn,int force_turn){return state!=CastleState::BUILT&&prerequisite&&(f.must_fund||started>=0||turn>=force_turn);}\ninline bool picker_start_allowed(int turn,int cooldown_until,int land,int touched,int reachable,bool general_confirmed,bool contacted){int need=std::max(1,std::min(reachable,5));return turn>=120&&turn>=cooldown_until&&land>=12&&(general_confirmed||contacted||touched>=need);}\nstruct Packet"
repl(core,old,new,'core compliance helpers')

repl(main,"EdgePickerState picker_;int edge_picker_threshold_=16,picker_wait_=0;double edge_picker_min_efficiency_=2.0;","EdgePickerState picker_;int edge_picker_threshold_=16,picker_wait_=0,picker_cooldown_until_=0;double edge_picker_min_efficiency_=2.0;",'picker cooldown state')

old="castle_latest_={f1.latest_start,f2.latest_start};castle_actions_={f1.required_actions,f2.required_actions};for(int i=0;i<2;++i)if((i?f2.must_fund:f1.must_fund)&&castle_start_[i]<0)castle_start_[i]=o.turn;if(o.turn>175&&castle_build_[0]<0)castle_miss_=f1.capacity<f1.required?\"c1_insufficient_army\":f1.required_actions>f1.turns?\"c1_action_infeasible\":\"c1_unavailable\";else if(o.turn>250&&castle_build_[1]<0)castle_miss_=f2.capacity<f2.required?\"c2_insufficient_army\":f2.required_actions>f2.turns?\"c2_action_infeasible\":\"c2_unavailable\";int c1reserve=(f1.feasible&&f1.must_fund)?f1.required:0;int c2reserve=(castle_state_[0]==CastleState::BUILT&&f2.feasible&&f2.must_fund)?f2.required:0;auto b=budget(o.my_army,general_>=0?o.army[general_]:0,c1reserve,c2reserve,confirmed_war,adapt.attack);if(production_==ProductionState::SEVERE_DEFICIT){b.expansion=std::max(b.expansion,b.free+b.search+b.war/2);b.search=0;b.war/=2;}"
new="castle_latest_={f1.latest_start,f2.latest_start};castle_actions_={f1.required_actions,f2.required_actions};for(int i=0;i<2;++i)if((i?f2.must_fund:f1.must_fund)&&castle_start_[i]<0)castle_start_[i]=o.turn;bool sticky_c1=castle_funding_active(castle_state_[0],true,f1,castle_start_[0],o.turn,120);bool sticky_c2=castle_funding_active(castle_state_[1],castle_state_[0]==CastleState::BUILT,f2,castle_start_[1],o.turn,205);if(sticky_c1&&castle_start_[0]<0)castle_start_[0]=o.turn;if(sticky_c2&&castle_start_[1]<0)castle_start_[1]=o.turn;if(o.turn>175&&castle_build_[0]<0)castle_miss_=f1.capacity<f1.required?\"c1_insufficient_army\":f1.required_actions>f1.turns?\"c1_action_infeasible\":\"c1_unavailable\";else if(o.turn>250&&castle_build_[1]<0)castle_miss_=f2.capacity<f2.required?\"c2_insufficient_army\":f2.required_actions>f2.turns?\"c2_action_infeasible\":\"c2_unavailable\";int c1reserve=sticky_c1?f1.required:0;int c2reserve=sticky_c2?f2.required:0;auto b=budget(o.my_army,general_>=0?o.army[general_]:0,c1reserve,c2reserve,confirmed_war,adapt.attack);if(production_==ProductionState::SEVERE_DEFICIT){b.expansion=std::max(b.expansion,b.free+b.search+b.war/2);bool need_explore=!belief_.confirmed()&&sector_touched_count()<search_reachable_count();b.search=need_explore?std::max(1,b.search):0;b.war/=2;}"
repl(main,old,new,'sticky castle funding and exploration floor')

old="for(auto [site,f,index]:{std::tuple{castles_.c1,f1,0},std::tuple{castles_.c2,f2,1}})if(site>=0&&castle_state_[index]!=CastleState::BUILT&&(index==0||castle_state_[0]==CastleState::BUILT)){bool c1=index==0,force_c1=c1&&o.turn>=120&&o.turn<=175;if(legal_build(o,site))c.push_back({c1?0:1,site,site,2,c1?7500.:100.,Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});else if(f.must_fund||force_c1)for(int x=0;x<n_;++x)if(source(o,x)){int y=tactical_next(o,x,site);if(y>=0)c.push_back({1,x,y,0,(force_c1?500.:0.)+double(o.army[x])/std::max(1,g_.dist[x][site]),Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});}}"
new="for(auto [site,f,index]:{std::tuple{castles_.c1,f1,0},std::tuple{castles_.c2,f2,1}})if(site>=0&&castle_state_[index]!=CastleState::BUILT&&(index==0||castle_state_[0]==CastleState::BUILT)){bool c1=index==0,funding=c1?sticky_c1:sticky_c2;if(legal_build(o,site))c.push_back({c1?0:1,site,site,2,c1?7500.:100.,Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});else if(funding)for(int x=0;x<n_;++x)if(source(o,x)){int y=tactical_next(o,x,site);if(y>=0)c.push_back({1,x,y,0,500.+double(o.army[x])/std::max(1,g_.dist[x][site]),Reason::CASTLE_DEADLINE,false,ActionClass::HARD,site,-1,index?PacketRole::CASTLE_C2:PacketRole::CASTLE_C1});}}"
repl(main,old,new,'sticky castle candidates')

repl(main,"if(picker_.active&&(picker_.cell<0||picker_.cell>=n_||o.owner[picker_.cell]!=1)){picker_.active=false;picker_wait_=0;++picker_aborts_;++picker_lost_aborts_;}","if(picker_.active&&(picker_.cell<0||picker_.cell>=n_||o.owner[picker_.cell]!=1)){picker_.active=false;picker_wait_=0;picker_cooldown_until_=std::max(picker_cooldown_until_,o.turn+25);++picker_aborts_;++picker_lost_aborts_;}",'picker lost cooldown')
repl(main,"else if(picker_.active&&o.army[picker_.cell]<=1){picker_.active=false;picker_wait_=0;++picker_aborts_;++picker_depleted_aborts_;}","else if(picker_.active&&o.army[picker_.cell]<=1){picker_.active=false;picker_wait_=0;picker_cooldown_until_=std::max(picker_cooldown_until_,o.turn+25);++picker_aborts_;++picker_depleted_aborts_;}",'picker depleted cooldown')
repl(main,"if(!picker_.active&&!immediate&&general_>=0){","if(!picker_.active&&!immediate&&general_>=0&&picker_start_allowed(o.turn,picker_cooldown_until_,o.my_land,sector_touched_count(),search_reachable_count(),belief_.confirmed(),meaningful_contact_turn_>=0)){",'picker exploration gate')

old="if(confirmed_war&&b.war>0)c.push_back({2,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::WAR_MOBILIZATION,false,ActionClass::LOGISTICS,target,front?front->id:-1,PacketRole::FRONT});else if(rear&&b.free+b.search>0)"
new="if(belief_.confirmed()&&!immediate)c.push_back({2,x,y,0,2000.+double(surplus)/std::max(1,g_.dist[x][target]),Reason::WAR_MOBILIZATION,false,ActionClass::OFFENSE,target,-1,PacketRole::ATTACK});else if(confirmed_war&&b.war>0)c.push_back({2,x,y,0,double(surplus)/std::max(1,g_.dist[x][target]),Reason::WAR_MOBILIZATION,false,ActionClass::LOGISTICS,target,front?front->id:-1,PacketRole::FRONT});else if(rear&&b.free+b.search>0)"
repl(main,old,new,'persistent confirmed-general attack')

repl(main,"q.reason!=Reason::GENERAL_EMERGENCY&&q.reason!=Reason::TERMINAL_CAPTURE","q.reason!=Reason::GENERAL_EMERGENCY&&q.reason!=Reason::TERMINAL_CAPTURE&&q.reason!=Reason::CASTLE_DEADLINE",'castle may preempt picker source')
repl(main,"std::array<double,5>share{{0,confirmed_war?.30:.12,","std::array<double,5>share{{0,(confirmed_war||belief_.confirmed())?.30:.12,",'confirmed-general offense share')
repl(main,"Candidate q;if(picker_.active&&critical_available){std::vector<Candidate>hv;","Candidate q;if(critical_available){std::vector<Candidate>hv;",'critical always beats forced search/picker')
repl(main,"picker_.active=false;picker_wait_=0;picker_.blocked_turns=0;++picker_completions_;","picker_.active=false;picker_wait_=0;picker_.blocked_turns=0;picker_cooldown_until_=std::max(picker_cooldown_until_,o.turn+40);++picker_completions_;",'picker completion cooldown')
old="}else if(picker_.active&&q.from==picker_.cell&&(q.reason==Reason::GENERAL_EMERGENCY||q.reason==Reason::TERMINAL_CAPTURE)){picker_.cell=q.to;picker_.phase=1;picker_.blocked_turns=0;++picker_critical_preempt_moves_;}commit_packet(o,q);"
new="}else if(picker_.active&&q.from==picker_.cell&&q.reason==Reason::CASTLE_DEADLINE){picker_.active=false;picker_wait_=0;picker_.blocked_turns=0;picker_cooldown_until_=std::max(picker_cooldown_until_,o.turn+40);++picker_aborts_;}else if(picker_.active&&q.from==picker_.cell&&(q.reason==Reason::GENERAL_EMERGENCY||q.reason==Reason::TERMINAL_CAPTURE)){picker_.cell=q.to;picker_.phase=1;picker_.blocked_turns=0;++picker_critical_preempt_moves_;}commit_packet(o,q);"
repl(main,old,new,'castle preempts active picker cleanly')

old="auto work=forecast(100,150,40,0,{{15,5},{15,6},{15,7}},false);assert(work.required_actions==5+6+7+1+1);assert(work.latest_start==150-work.required_actions-5);"
new="auto work=forecast(100,150,40,0,{{15,5},{15,6},{15,7}},false);assert(work.required_actions==5+6+7+1+1);assert(work.latest_start==150-work.required_actions-5);FundingForecast infeasible;infeasible.must_fund=false;assert(castle_funding_active(CastleState::PLANNED,true,infeasible,130,220,120));assert(!castle_funding_active(CastleState::BUILT,true,infeasible,130,220,120));assert(picker_start_allowed(150,0,20,5,9,false,false));assert(!picker_start_allowed(150,0,5,5,9,false,false));assert(!picker_start_allowed(150,200,20,5,9,false,false));"
repl(test,old,new,'compliance helper tests')
repl(test,'v35 core: 24 behavioral checks passed','v35 core: 29 behavioral checks passed','core test count')

old='// Confirmed general remains exact despite later fog.\n {Agent a(0,21,21);auto o=board();o.type[230]=4;o.owner[230]=2;o.army[230]=3;o.owner[229]=1;o.army[229]=1;a.decide(o);assert(a.enemy_general_confirmed()&&a.enemy_general_cell()==230);o.turn++;o.type[230]=-1;o.owner[230]=-1;a.decide(o);assert(a.enemy_general_cell()==230);}'
new='// Confirmed general remains exact despite later fog.\n {Agent a(0,21,21);auto o=board();o.type[230]=4;o.owner[230]=2;o.army[230]=3;o.owner[229]=1;o.army[229]=1;a.decide(o);assert(a.enemy_general_confirmed()&&a.enemy_general_cell()==230);o.turn++;o.type[230]=-1;o.owner[230]=-1;a.decide(o);assert(a.enemy_general_cell()==230);}\n // Once the enemy general is confirmed, a quiet front still produces forward attack progress.\n {Agent a(0,21,21);auto o=board();for(int x=0;x<441;++x)if(x!=220){o.owner[x]=1;o.army[x]=1;}o.type[230]=4;o.owner[230]=2;o.army[230]=3;o.army[220]=20;o.my_land=440;o.my_army=459;o.opp_land=1;o.opp_army=3;auto q=a.decide(o);assert(q.kind==0);int s=src(q),d=dst(q);auto md=[](int x){return std::abs(x/21-230/21)+std::abs(x%21-230%21);};assert(md(d)<md(s));}'
repl(testa,old,new,'confirmed-general attack regression')

print('V3.6 compliance patch complete')
